const fs = require('fs')
const path = require('path')

const CLUBS = {
  'club-cp': { id: 'club-cp', name: 'CP Club', color: '#2F4BD6', verified: true },
  'club-ai': { id: 'club-ai', name: 'AIONAI', color: '#7B63A8', verified: true },
  'club-birds': { id: 'club-birds', name: 'BIRDS', color: '#6F8468', verified: true },
  'club-devcraft': { id: 'club-devcraft', name: 'DevCraft', color: '#C66A4A', verified: true },
  'club-robocrafters': { id: 'club-robocrafters', name: 'Robocrafters', color: '#B85D19', verified: false },
  'club-cyberguard': { id: 'club-cyberguard', name: 'CyberGuard', color: '#1F5F5B', verified: true },
  'club-nexiot': { id: 'club-nexiot', name: 'NexIoT', color: '#E3A12F', verified: false },
  'club-pixelforge': { id: 'club-pixelforge', name: 'PixelForge', color: '#5B2A4A', verified: true },
  'club-foss': { id: 'club-foss', name: 'FOSS Society', color: '#A32828', verified: true },
}

const CLUB_KEYS = Object.keys(CLUBS)

const PROMOTED_EVENTS = [
  {
    id: 'evt-1',
    slug: 'grand-turing-hackathon-2026',
    orgId: 'org-1',
    organizerId: 'club-cp',
    organizerName: 'CP Club',
    organizerColor: '#2F4BD6',
    club: CLUBS['club-cp'],
    isSignature: true,
    title: 'THE GRAND TURING HACKATHON 2026',
    subtitle: 'Annual 48-Hour Systems & Algorithmic Endurance Hackathon',
    category: 'hackathon',
    type: 'hackathon',
    tags: ['Algorithms', 'Systems', 'Distributed', 'Cash Prize', 'Flagship'],
    description:
      'The premier algorithmic hackathon of the Autumn edition. 48 hours of relentless engineering where 60 curated teams build distributed protocols, high-frequency execution engines, and algorithmic intelligence. Peer-reviewed evaluation by industry staff engineers and research faculty.',
    poster: '/images/events/event-1.webp',
    banner: '/images/events/event-1.webp',
    venue: {
      name: 'Campus Main Auditorium',
      address: 'Central Academic Complex, Engineering Pavilion',
      mapUrl: 'https://maps.google.com',
    },
    startsAt: '2026-10-24T09:00:00Z',
    endsAt: '2026-10-26T12:00:00Z',
    eligibility: 'Open to all engineering cohorts and verified developers. Teams of 2 to 4.',
    capacity: 250,
    seatsLeft: 34,
    waitlistEnabled: true,
    registrationOpensAt: '2026-10-01T00:00:00Z',
    registrationClosesAt: '2026-10-22T23:59:00Z',
    schedule: [
      { time: '09:00 AM · DAY 1', title: 'Curatorial Keynote & Problem Space Reveal' },
      { time: '11:00 AM · DAY 1', title: 'Hacking Commences & Architecture Checkpoints' },
      { time: '02:00 AM · DAY 2', title: 'Midnight Algorithmic Stress Benchmark' },
      { time: '09:00 AM · DAY 3', title: 'Code Freeze & Jury Deliberation' },
      { time: '12:00 PM · DAY 3', title: 'Grand Exhibition & Award Conferment' },
    ],
    people: [
      {
        name: 'Dr. Vikramaditya Sen',
        role: 'judge',
        bio: 'Distributed Systems Chair & Principal Investigator.',
      },
      {
        name: 'Tara Venkatesh',
        role: 'judge',
        bio: 'Staff Systems Architect at Global Scale Compute.',
      },
    ],
    rules: [
      'All production code and repositories must be initiated during the hackathon hours.',
      'Open-source libraries and public frameworks are permitted; commercial APIs must be declared.',
      'Submissions require reproducible unit test coverage and architecture documentation.',
    ],
    contact: {
      name: 'Sameer Kulkarni',
      phone: '+91 98450 12345',
      email: 'lead@cpclub.org',
    },
    certificateInfo: 'Verifiable Certificate of Distinction and Cash Grant awarded to winners.',
    features: {
      certificate: true,
      checkin: true,
      paid: false,
      team: true,
    },
    teamConfig: { minSize: 2, maxSize: 4 },
    formSchema: [
      { id: 'f-github', type: 'text', label: 'GitHub Organization or Profile URL', required: true },
      { id: 'f-track', type: 'select', label: 'Preferred Track', options: ['Distributed Protocols', 'AI & Neural Engines', 'Security & Cryptography'], required: true },
      { id: 'f-exp', type: 'longtext', label: 'Prior Systems or Competitive Coding Background', required: false },
    ],
    status: 'published',
    results: [],
    photos: [],
    promotion: {
      label: 'Promoted',
      priority: 5,
      startsAt: '2026-10-01T00:00:00Z',
      endsAt: '2026-11-01T00:00:00Z',
    },
    publishedAt: '2026-10-08T09:00:00Z',
    registrationsCount: 216,
    isFree: true,
    price: 0,
    createdAt: '2026-10-01T10:00:00Z',
  },
  {
    id: 'evt-2',
    slug: 'neural-frontiers-symposium-2026',
    orgId: 'org-1',
    organizerId: 'club-ai',
    organizerName: 'AIONAI',
    organizerColor: '#7B63A8',
    club: CLUBS['club-ai'],
    isSignature: true,
    title: 'NEURAL FRONTIERS RESEARCH SYMPOSIUM',
    subtitle: 'State of Frontier Generative Models, Interpretability & Multimodal Vision',
    category: 'talk',
    type: 'talk',
    tags: ['AI', 'Research', 'Keynote', 'Symposium', 'Flagship'],
    description:
      'A full-day scholarly dialogue bringing together neural architects, foundation model researchers, and compute practitioners. Deep dive presentations on mechanistic interpretability, diffusion formulations, and efficient model alignment.',
    poster: '/images/events/event-2.webp',
    banner: '/images/events/event-2.webp',
    venue: {
      name: 'Turing Computer Lab & Main Stage',
      address: 'Computing Pavilion, Floor 3',
      mapUrl: 'https://maps.google.com',
    },
    startsAt: '2026-10-18T09:30:00Z',
    endsAt: '2026-10-18T18:00:00Z',
    eligibility: 'Open to researchers, students, and engineers.',
    capacity: 180,
    seatsLeft: 12,
    waitlistEnabled: true,
    registrationOpensAt: '2026-10-01T00:00:00Z',
    registrationClosesAt: '2026-10-16T23:59:00Z',
    schedule: [
      { time: '09:30 AM', title: 'Opening Remarks & Compute Landscape Address' },
      { time: '11:00 AM', title: 'Mechanistic Circuits in Large Language Decoders' },
      { time: '02:00 PM', title: 'Hardware Acceleration & Speculative Sampling Salon' },
      { time: '04:30 PM', title: 'Curatorial Panel: The Trajectory of Open Weights' },
    ],
    people: [
      {
        name: 'Dr. Leena Varma',
        role: 'speaker',
        bio: 'Faculty Chair, Neural Systems Laboratory.',
      },
    ],
    rules: ['Chatham House Rule applies during closed-door breakout forums.'],
    contact: {
      name: 'Nikhil Menon',
      email: 'chair@aionai.org',
    },
    certificateInfo: 'Verifiable Certificate of Scholarly Attendance.',
    features: {
      certificate: true,
      checkin: true,
      paid: false,
      team: false,
    },
    formSchema: [
      { id: 'f-inst', type: 'text', label: 'Academic Department or Laboratory Affiliation', required: true },
      { id: 'f-interest', type: 'text', label: 'Primary Research Domain', required: true },
    ],
    status: 'published',
    results: [],
    photos: [],
    promotion: {
      label: 'Promoted',
      priority: 4,
      startsAt: '2026-10-01T00:00:00Z',
      endsAt: '2026-11-01T00:00:00Z',
    },
    publishedAt: '2026-10-07T14:30:00Z',
    registrationsCount: 168,
    isFree: true,
    price: 0,
    createdAt: '2026-10-01T10:00:00Z',
  },
  {
    id: 'evt-3',
    slug: 'biomimetic-swarm-kinematics-workshop',
    orgId: 'org-1',
    organizerId: 'club-birds',
    organizerName: 'BIRDS',
    organizerColor: '#6F8468',
    club: CLUBS['club-birds'],
    isSignature: false,
    title: 'BIOMIMETIC SWARM KINEMATICS WORKSHOP',
    subtitle: 'Hands-on Autonomous Micro-Robotics & Insect Flight Mechanics',
    category: 'workshop',
    type: 'workshop',
    tags: ['Robotics', 'Bio-inspired', 'Hardware', 'Sensors'],
    description:
      'Construct and calibrate bio-inspired flapping-wing autonomous systems. Includes real-time sensor fusion using micro-optical flow cameras and custom brushless motor speed controllers.',
    poster: '/images/events/event-3.webp',
    venue: {
      name: 'Mechatronics Pavilion Flight Arena',
      address: 'Aeronautics Block B',
    },
    startsAt: '2026-10-21T10:00:00Z',
    endsAt: '2026-10-21T17:00:00Z',
    eligibility: 'Intermediate hardware proficiency recommended.',
    capacity: 90,
    seatsLeft: 4, // triggers "Filling fast" (< 5)
    waitlistEnabled: true,
    registrationOpensAt: '2026-10-01T00:00:00Z',
    registrationClosesAt: '2026-10-19T23:59:00Z',
    schedule: [
      { time: '10:00 AM', title: 'Piezoelectric Actuators & Wing Dynamics Theory' },
      { time: '01:00 PM', title: 'Soldering & Microcontroller Firmware Flashing' },
      { time: '03:30 PM', title: 'Indoor Autonomous Arena Obstacle Trials' },
    ],
    people: [
      {
        name: 'Tara Nair',
        role: 'instructor',
        bio: 'Robotics Lead & Autonomous Flight Researcher.',
      },
    ],
    rules: ['Safety goggles mandatory in the arena at all times.'],
    contact: {
      name: 'Karthik Balan',
      email: 'lead@birds.org',
    },
    certificateInfo: 'Hardware Lab Certification Issued.',
    features: {
      certificate: true,
      checkin: true,
      paid: false,
      team: false,
    },
    formSchema: [],
    status: 'published',
    results: [],
    photos: [],
    promotion: {
      label: 'Promoted',
      priority: 3,
      startsAt: '2026-10-01T00:00:00Z',
      endsAt: '2026-11-01T00:00:00Z',
    },
    publishedAt: '2026-10-06T11:00:00Z',
    registrationsCount: 86,
    isFree: true,
    price: 0,
    createdAt: '2026-10-01T10:00:00Z',
  },
  {
    id: 'evt-4',
    slug: 'zero-day-exploit-ctf-2026',
    orgId: 'org-1',
    organizerId: 'club-cyberguard',
    organizerName: 'CyberGuard',
    organizerColor: '#1F5F5B',
    club: CLUBS['club-cyberguard'],
    isSignature: true,
    title: 'ZERO-DAY PROTOCOL CTF 2026',
    subtitle: 'Competitive Offensive Security & Reverse Engineering Tournament',
    category: 'competition',
    type: 'competition',
    tags: ['Security', 'Reverse Engineering', 'CTF', 'Pwn', 'Cryptography'],
    description:
      '12-hour high-tempo offensive security showdown. Challenges cover heap exploitation, ARM firmware vulnerabilities, post-quantum cryptographic primitives, and smart contract protocol re-entrancy.',
    poster: '/images/events/event-4.webp',
    venue: {
      name: 'Cybersecurity Isolation Lab',
      address: 'Security Complex, Floor 1',
    },
    startsAt: '2026-10-28T09:00:00Z',
    endsAt: '2026-10-28T21:00:00Z',
    eligibility: 'Solo or duos.',
    capacity: 200,
    seatsLeft: 5, // triggers "Filling fast"
    waitlistEnabled: true,
    registrationOpensAt: '2026-10-01T00:00:00Z',
    registrationClosesAt: '2026-10-26T23:59:00Z',
    schedule: [
      { time: '09:00 AM', title: 'Network Access Release & Environment Brief' },
      { time: '09:30 AM', title: 'Flags Live: Jeopardy & Attack-Defense Board' },
      { time: '08:30 PM', title: 'Scoreboard Freeze & Solution Validation' },
    ],
    people: [
      {
        name: 'Pranav Nair',
        role: 'judge',
        bio: 'CTF Captain & Kernel Security Specialist.',
      },
    ],
    rules: [
      'Denial of service against competition scoring infrastructure is strictly forbidden.',
      'Flag sharing between distinct registered teams disqualifies both.',
    ],
    contact: {
      name: 'Divya Krishnan',
      email: 'lead@cyberguard.org',
    },
    certificateInfo: 'Verifiable Proof-of-Skill Certificate of Distinction.',
    features: {
      certificate: true,
      checkin: true,
      paid: false,
      team: true,
    },
    teamConfig: { minSize: 1, maxSize: 2 },
    formSchema: [],
    status: 'published',
    results: [],
    photos: [],
    promotion: {
      label: 'Promoted',
      priority: 2,
      startsAt: '2026-10-01T00:00:00Z',
      endsAt: '2026-11-01T00:00:00Z',
    },
    publishedAt: '2026-10-05T16:00:00Z',
    registrationsCount: 195,
    isFree: true,
    price: 0,
    createdAt: '2026-10-01T10:00:00Z',
  },
  {
    id: 'evt-5',
    slug: 'devcraft-architecture-retreat',
    orgId: 'org-1',
    organizerId: 'club-devcraft',
    organizerName: 'DevCraft',
    organizerColor: '#C66A4A',
    club: CLUBS['club-devcraft'],
    isSignature: false,
    title: 'DEVCRAFT ARCHITECTURE RETREAT',
    subtitle: 'High-Concurrency Distributed Systems & Resilient Infrastructure',
    category: 'workshop',
    type: 'workshop',
    tags: ['Architecture', 'Distributed Systems', 'Kafka', 'Golang'],
    description:
      'Masterclass on event-driven architectures, write-ahead logs, and database sharding under multi-million message throughputs. Practical implementations built in Go and RocksDB.',
    poster: '/images/events/event-5.webp',
    venue: {
      name: 'Distributed Systems Studio',
      address: 'Software Engineering Annex',
    },
    startsAt: '2026-10-30T10:00:00Z',
    endsAt: '2026-10-31T18:00:00Z',
    eligibility: 'Engineers with familiarity with backend concurrency primitives.',
    capacity: 120,
    seatsLeft: 8,
    waitlistEnabled: true,
    registrationOpensAt: '2026-10-01T00:00:00Z',
    registrationClosesAt: '2026-10-28T23:59:00Z',
    schedule: [
      { time: '10:00 AM · DAY 1', title: 'Consensus Engines: Raft vs Multi-Paxos' },
      { time: '02:00 PM · DAY 1', title: 'LSM-Trees and Lockless Ring Buffer Optimization' },
      { time: '10:00 AM · DAY 2', title: 'Network Partition Simulation & Split-Brain Drills' },
    ],
    people: [
      {
        name: 'Siddharth Roy',
        role: 'instructor',
        bio: 'Core Infrastructure Lead at DevCraft.',
      },
    ],
    rules: ['Bring your own Unix-like dev environment.'],
    contact: {
      name: 'Siddharth Roy',
      email: 'lead@devcraft.org',
    },
    certificateInfo: 'Advanced Systems Specialization Credential Issued.',
    features: {
      certificate: true,
      checkin: true,
      paid: true,
      team: false,
    },
    formSchema: [],
    status: 'published',
    results: [],
    photos: [],
    promotion: {
      label: 'Promoted',
      priority: 1,
      startsAt: '2026-10-01T00:00:00Z',
      endsAt: '2026-11-01T00:00:00Z',
    },
    publishedAt: '2026-10-04T10:00:00Z',
    registrationsCount: 112,
    isFree: false,
    price: 299,
    createdAt: '2026-10-01T10:00:00Z',
  },
]

const REMAINING_HANDCRAFTED = [
  {
    id: 'evt-6',
    slug: 'combat-robotics-arena-qualifiers',
    orgId: 'org-1',
    organizerId: 'club-robocrafters',
    organizerName: 'Robocrafters',
    organizerColor: '#B85D19',
    club: CLUBS['club-robocrafters'],
    isSignature: false,
    title: 'COMBAT ROBOTICS ARENA QUALIFIERS',
    subtitle: 'Kinetic Weapon Systems & Heavyweight Chassis Showdown',
    category: 'competition',
    type: 'competition',
    tags: ['Robotics', 'Hardware', 'Combat', 'Fabrication'],
    description:
      'Qualifying rounds for the 15kg featherweight combat arena. Dual-drum spinners, titanium chassis wedges, and remote telemetry fail-safes tested in bulletproof Lexan containment.',
    poster: '/images/events/event-6.webp',
    venue: { name: 'Outdoor Fabrication Courtyard', address: 'Mech Annex 1' },
    startsAt: '2026-11-02T13:00:00Z',
    endsAt: '2026-11-02T19:00:00Z',
    eligibility: 'Registered mechatronics collectives.',
    capacity: 150,
    seatsLeft: 22,
    waitlistEnabled: true,
    registrationOpensAt: '2026-10-05T00:00:00Z',
    registrationClosesAt: '2026-10-30T23:59:00Z',
    schedule: [{ time: '01:00 PM', title: 'Safety Inspections & Weapon Lock Verification' }],
    people: [{ name: 'Vikram Seth', role: 'judge', bio: 'Combat Robotics Lead.' }],
    rules: ['Active fail-safe radio kill switch mandatory.'],
    contact: { name: 'Vikram Seth', email: 'lead@robocrafters.org' },
    certificateInfo: 'Tournament Merit Certificate Issued.',
    features: { certificate: true, checkin: true, paid: false, team: true },
    formSchema: [],
    status: 'published',
    results: [],
    photos: [],
    publishedAt: '2026-10-03T09:00:00Z',
    registrationsCount: 128,
    isFree: true,
    price: 0,
    createdAt: '2026-10-01T10:00:00Z',
  },
  {
    id: 'evt-7',
    slug: 'pervasive-lorawan-sensor-mesh',
    orgId: 'org-1',
    organizerId: 'club-nexiot',
    organizerName: 'NexIoT',
    organizerColor: '#E3A12F',
    club: CLUBS['club-nexiot'],
    isSignature: false,
    title: 'PERVASIVE LORAWAN SENSOR MESH',
    subtitle: 'Deploying Sub-Gigahertz Long-Range Telemetry Nodes Across Campus',
    category: 'workshop',
    type: 'workshop',
    tags: ['IoT', 'LoRaWAN', 'Embedded', 'Hardware'],
    description:
      'Field deployment workshop configuring solar-harvesting ESP32 nodes communicating via 868MHz LoRa packets to a centralized Grafana dashboard over The Things Network.',
    poster: '/images/events/event-7.webp',
    venue: { name: 'Embedded Communications Lab', address: 'Electrical Sciences Block' },
    startsAt: '2026-11-05T10:00:00Z',
    endsAt: '2026-11-05T16:00:00Z',
    eligibility: 'All students with basic C++ or MicroPython experience.',
    capacity: 80,
    seatsLeft: 18,
    waitlistEnabled: true,
    registrationOpensAt: '2026-10-05T00:00:00Z',
    registrationClosesAt: '2026-11-03T23:59:00Z',
    schedule: [{ time: '10:00 AM', title: 'Sub-GHz RF Propagation & Antenna Tuning' }],
    people: [{ name: 'Harsh Vardhan', role: 'instructor', bio: 'NexIoT Lead.' }],
    rules: ['Equipment provided in lab kit.'],
    contact: { name: 'Harsh Vardhan', email: 'lead@nexiot.org' },
    certificateInfo: 'IoT Engineering Certificate Issued.',
    features: { certificate: true, checkin: true, paid: false, team: false },
    formSchema: [],
    status: 'published',
    results: [],
    photos: [],
    publishedAt: '2026-10-02T12:00:00Z',
    registrationsCount: 62,
    isFree: true,
    price: 0,
    createdAt: '2026-10-01T10:00:00Z',
  },
  {
    id: 'evt-8',
    slug: 'generative-graphics-and-shader-lab',
    orgId: 'org-1',
    organizerId: 'club-pixelforge',
    organizerName: 'PixelForge',
    organizerColor: '#5B2A4A',
    club: CLUBS['club-pixelforge'],
    isSignature: false,
    title: 'GENERATIVE GRAPHICS & SHADER LAB',
    subtitle: 'Creative Coding in GLSL, Raymarching, and Signed Distance Fields',
    category: 'workshop',
    type: 'workshop',
    tags: ['Creative Coding', 'Design', 'Shaders', 'WebGL'],
    description:
      'Learn raymarching mathematics, volumetric lighting, fractal repetition, and post-processing filters rendered in real-time inside WebGL fragment shaders.',
    poster: '/images/events/event-8.webp',
    venue: { name: 'Design Pavilion Studio 4', address: 'Arts & Media Wing' },
    startsAt: '2026-11-08T14:00:00Z',
    endsAt: '2026-11-08T19:00:00Z',
    eligibility: 'Open to designers and developers.',
    capacity: 75,
    seatsLeft: 3, // triggers "Filling fast"
    waitlistEnabled: true,
    registrationOpensAt: '2026-10-05T00:00:00Z',
    registrationClosesAt: '2026-11-06T23:59:00Z',
    schedule: [{ time: '02:00 PM', title: 'Math as Canvas: Vector Fields and SDFs' }],
    people: [{ name: 'Aryan Kapoor', role: 'instructor', bio: 'PixelForge Lead.' }],
    rules: ['Modern WebGL2-compatible laptop required.'],
    contact: { name: 'Aryan Kapoor', email: 'lead@pixelforge.org' },
    certificateInfo: 'Creative Technology Credential Issued.',
    features: { certificate: true, checkin: true, paid: false, team: false },
    formSchema: [],
    status: 'published',
    results: [],
    photos: [],
    publishedAt: '2026-10-01T15:00:00Z',
    registrationsCount: 72,
    isFree: true,
    price: 0,
    createdAt: '2026-10-01T10:00:00Z',
  },
  {
    id: 'evt-9',
    slug: 'software-freedom-day-kernel-salon',
    orgId: 'org-1',
    organizerId: 'club-foss',
    organizerName: 'FOSS Society',
    organizerColor: '#A32828',
    club: CLUBS['club-foss'],
    isSignature: false,
    title: 'SOFTWARE FREEDOM DAY & KERNEL SALON',
    subtitle: 'Linux Kernel Patching, eBPF Observability & Open Firmware',
    category: 'talk',
    type: 'talk',
    tags: ['Open Source', 'Linux', 'Kernel', 'eBPF'],
    description:
      'Community unconference celebrating open source infrastructure. Discussions on submitting upstream kernel patches, eBPF tracepoints, and building non-proprietary computing stacks.',
    poster: '/images/events/event-9.webp',
    venue: { name: 'Open Source Amphitheater', address: 'Computing Block Garden' },
    startsAt: '2026-11-12T11:00:00Z',
    endsAt: '2026-11-12T17:00:00Z',
    eligibility: 'Open to the public.',
    capacity: 200,
    seatsLeft: 84,
    waitlistEnabled: true,
    registrationOpensAt: '2026-10-05T00:00:00Z',
    registrationClosesAt: '2026-11-11T23:59:00Z',
    schedule: [{ time: '11:00 AM', title: 'Why Copyleft Matters for AI Foundations' }],
    people: [{ name: 'Varun Swaminathan', role: 'speaker', bio: 'FOSS Lead.' }],
    rules: ['Respect open source code of conduct.'],
    contact: { name: 'Varun Swaminathan', email: 'lead@foss.org' },
    certificateInfo: 'Participation Certificate Issued.',
    features: { certificate: true, checkin: true, paid: false, team: false },
    formSchema: [],
    status: 'published',
    results: [],
    photos: [],
    publishedAt: '2026-09-28T10:00:00Z',
    registrationsCount: 116,
    isFree: true,
    price: 0,
    createdAt: '2026-10-01T10:00:00Z',
  },
  {
    id: 'evt-10',
    slug: 'quantum-computing-algorithms-draft',
    orgId: 'org-1',
    organizerId: 'club-cp',
    organizerName: 'CP Club',
    organizerColor: '#2F4BD6',
    club: CLUBS['club-cp'],
    isSignature: false,
    title: 'QUANTUM GATES & SHOR ALGORITHM LAB (DRAFT)',
    subtitle: 'Qiskit Simulation of Fault-Tolerant Factoring',
    category: 'workshop',
    type: 'workshop',
    tags: ['Quantum', 'Algorithms', 'Draft'],
    description: 'Upcoming draft event undergoing internal review by club coordinators.',
    poster: '', // Intentional empty poster to test typographic poster fallback!
    venue: { name: 'Turing Computer Lab' },
    startsAt: '2026-12-01T10:00:00Z',
    endsAt: '2026-12-01T16:00:00Z',
    eligibility: 'All students',
    capacity: 50,
    seatsLeft: 50,
    waitlistEnabled: true,
    registrationOpensAt: '2026-11-15T00:00:00Z',
    registrationClosesAt: '2026-11-30T23:59:00Z',
    schedule: [],
    people: [],
    rules: [],
    contact: { name: 'Sameer Kulkarni', email: 'lead@cpclub.org' },
    certificateInfo: 'Certificate upon completion',
    features: { certificate: true, checkin: true, paid: false, team: false },
    formSchema: [],
    status: 'draft',
    results: [],
    photos: [],
    publishedAt: '2026-09-20T10:00:00Z',
    registrationsCount: 0,
    isFree: true,
    price: 0,
    createdAt: '2026-10-01T10:00:00Z',
  },
]

// 28 more events to reach 38 total events!
const PROCEDURAL_TITLES = [
  { title: 'GRAPH THEORY & HEURISTIC SEARCH SALON', type: 'workshop', cat: 'workshop', desc: 'Exploration of A* optimization, min-cut max-flow variants, and planar graphs.', paid: false, price: 0 },
  { title: 'LATENCY-CRITICAL RUST ENGINE BUILD', type: 'workshop', cat: 'workshop', desc: 'Zero-cost abstractions, memory fences, and lock-free ring buffers in modern Rust.', paid: true, price: 199 },
  { title: 'DEEP GENERATIVE AUDIO SYNTHESIS', type: 'talk', cat: 'talk', desc: 'State-space diffusion models applied to parametric music and speech synthesis.', paid: false, price: 0 },
  { title: 'BIOMIMETIC FLIGHT SENSORS SHOWCASE', type: 'other', cat: 'club_events', desc: 'Demonstration of strain-gauge synthetic insect wings and optical feedback control.', paid: false, price: 0 },
  { title: 'KUBERNETES AT SCALE CRASH DRILL', type: 'workshop', cat: 'workshop', desc: 'Hands-on cluster chaos testing with Cilium eBPF network observability.', paid: false, price: 0 },
  { title: 'AUTONOMOUS SUBMERSIBLE NAVIGATION', type: 'workshop', cat: 'workshop', desc: 'Acoustic positioning and visual SLAM underwater navigation algorithms.', paid: false, price: 0 },
  { title: 'ZERO-KNOWLEDGE PROOF CIRCUIT LAB', type: 'workshop', cat: 'workshop', desc: 'Writing Circom circuits for verifiable computations and Groth16 zk-SNARK proofs.', paid: true, price: 499 },
  { title: 'SMART POWER GRID TELEMETRY FORUM', type: 'talk', cat: 'talk', desc: 'Edge processing for distributed photovoltaic load estimation and phase balancing.', paid: false, price: 0 },
  { title: 'VARIABLE FONT DESIGN WORKSHOP', type: 'workshop', cat: 'workshop', desc: 'Drawing bezier axes, designing optical weights, and compiling OpenType font binaries.', paid: false, price: 0, emptyPoster: true },
  { title: 'SELF-HOSTED MATRIX CHAT FEDERATION', type: 'workshop', cat: 'workshop', desc: 'Decentralized communication infrastructure setup using Synapse and Rust conduits.', paid: false, price: 0 },
  { title: 'ICPC REGIONAL WARMUP CONTEST', type: 'competition', cat: 'competition', desc: '5-hour 12-problem contest with live scoreboard and post-contest editorial analysis.', paid: false, price: 0 },
  { title: 'EMBEDDED VISION WITH EDGE TPUs', type: 'workshop', cat: 'workshop', desc: 'Real-time object segmentation on Google Coral and Hailo-8 acceleration chips.', paid: false, price: 0 },
  { title: 'FIRMWARE REVERSE ENGINEERING MASTERCLASS', type: 'workshop', cat: 'workshop', desc: 'Dumping SPI flash, Ghidra decompilation of ARM Cortex-M microcode.', paid: true, price: 349 },
  { title: 'PNEUMATIC HIGH-PRESSURE COMBAT WEAPONS', type: 'workshop', cat: 'workshop', desc: 'Machining high-flow solenoid valves and nitrogen tank safety protocols.', paid: false, price: 0 },
  { title: 'BRUTALIST WEB ARCHITECTURE SYMPOSIUM', type: 'talk', cat: 'talk', desc: 'Architectural dialogue on semantic minimalism, zero JavaScript fallbacks, and craft.', paid: false, price: 0, emptyPoster: true },
  { title: 'OPEN SCIENCE DATA REPRODUCIBILITY DAY', type: 'other', cat: 'club_events', desc: 'Publishing reproducible Jupyter notebooks, Nix flakes, and Zenodo DOI registries.', paid: false, price: 0 },
  { title: 'DISTRIBUTED CONSENSUS RAFT ALGORITHMS', type: 'workshop', cat: 'workshop', desc: 'Implementing leader election, log replication, and split-brain recovery from scratch.', paid: false, price: 0 },
  { title: 'NEURAL TEXT DECODER BENCHMARK SPRINT', type: 'hackathon', cat: 'hackathon', desc: '24-hour sprint to build the fastest speculative decoding inference engine.', paid: false, price: 0 },
  { title: 'ROBOTIC ARM INVERSE KINEMATICS CRITIQUE', type: 'other', cat: 'completed', desc: 'Evaluation of 6-DoF Stewart platforms and closed-loop PID control loops.', paid: false, price: 0 },
  { title: 'CYBERSECURITY FORENSICS & MEMORY DUMPS', type: 'workshop', cat: 'completed', desc: 'Volatility framework analysis of memory dumps during active rootkit execution.', paid: false, price: 0 },
  { title: 'POST-QUANTUM LATTICE CRYPTOGRAPHY ROUNDTABLE', type: 'talk', cat: 'talk', desc: 'Kyber and Dilithium mathematical foundations and NIST standardization roadmaps.', paid: false, price: 0 },
  { title: 'HARDWARE ACCELERATED RAY TRACING SPRINT', type: 'hackathon', cat: 'hackathon', desc: 'Building custom BVH traversal cores in SystemVerilog for FPGA simulation.', paid: false, price: 0 },
  { title: 'MICRO-FRONTENDS & ISLAND ARCHITECTURES', type: 'workshop', cat: 'workshop', desc: 'Decomposing colossal web codebases using Module Federation and web components.', paid: false, price: 0 },
  { title: 'BIOLOGICAL NEURAL NETWORKS & SYNAPSE CHIPS', type: 'talk', cat: 'talk', desc: 'Neuromorphic spike timing-dependent plasticity modeled on Loihi neuromorphic silicon.', paid: false, price: 0 },
  { title: 'SPEED-CODING LIGHTNING DUEL III', type: 'competition', cat: 'competition', desc: 'Single-elimination speed coding bracket tournament under intense spectator commentary.', paid: false, price: 0 },
  { title: 'OFFENSIVE WEB RECONNAISSANCE AT SCALE', type: 'workshop', cat: 'workshop', desc: 'Automating mass ASN mapping, sub-domain discovery pipelines, and cloud bucket audits.', paid: true, price: 249 },
  { title: 'ACCESSIBLE TYPE & COLOR DYNAMICS SALON', type: 'talk', cat: 'talk', desc: 'APCA contrast algorithms, WCAG 3.0 perceptual color spaces, and variable typeface optics.', paid: false, price: 0, emptyPoster: true },
  { title: 'ENERGY-HARVESTING SMART MESH DRILL', type: 'other', cat: 'club_events', desc: 'Field testing thermo-electric and piezoelectric power modules for outdoor sensor swarms.', paid: false, price: 0 },
]

const ALL_EVENTS = [...PROMOTED_EVENTS, ...REMAINING_HANDCRAFTED]

for (let i = 0; i < PROCEDURAL_TITLES.length; i++) {
  const item = PROCEDURAL_TITLES[i]
  const clubId = CLUB_KEYS[(i + 2) % CLUB_KEYS.length]
  const clubMeta = CLUBS[clubId]
  const id = `evt-${i + 11}`
  const slug = item.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
  const isCompleted = item.cat === 'completed'
  const isDraft = i === 16

  // Local image index 10 through 24
  const imgIdx = ((i + 9) % 24) + 1
  const poster = item.emptyPoster ? '' : `/images/events/event-${imgIdx}.webp`
  
  // Date calculation: distribute between upcoming days
  const dayOffset = (i % 25) + 2
  const startsAt = isCompleted
    ? '2026-08-14T10:00:00Z'
    : `2026-11-${String(dayOffset).padStart(2, '0')}T10:00:00Z`
  const endsAt = isCompleted
    ? '2026-08-14T16:00:00Z'
    : `2026-11-${String(dayOffset).padStart(2, '0')}T16:00:00Z`

  const capacity = 60 + ((i * 15) % 150)
  const seatsLeft = isCompleted ? 0 : (i % 7 === 0) ? 2 : 15 + (i % 30) // some trigger filling fast

  ALL_EVENTS.push({
    id,
    slug,
    orgId: 'org-1',
    organizerId: clubId,
    organizerName: clubMeta.name,
    organizerColor: clubMeta.color,
    club: clubMeta,
    isSignature: false,
    title: item.title,
    subtitle: `Curated by ${clubMeta.name}`,
    category: item.cat,
    type: item.type,
    tags: [clubMeta.name, item.cat.toUpperCase()],
    description: item.desc,
    poster,
    banner: poster || undefined,
    venue: { name: 'Campus Main Auditorium', address: 'Academic Quadrangle' },
    startsAt,
    endsAt,
    eligibility: 'Open to all registered student collectives',
    capacity,
    seatsLeft,
    waitlistEnabled: true,
    registrationOpensAt: '2026-10-01T00:00:00Z',
    registrationClosesAt: '2026-11-20T23:59:00Z',
    schedule: [{ time: '10:00 AM', title: 'Curatorial Introduction & Technical Scope' }],
    people: [{ name: 'Lead Curator', role: 'instructor', bio: 'Technical Association Fellow.' }],
    rules: ['All engineering artifacts must be reproducible and open.'],
    contact: { name: 'Club Lead', email: `lead@${clubId}.org` },
    certificateInfo: 'Verifiable Certificate of Participation Issued.',
    features: { certificate: true, checkin: true, paid: item.paid, team: false },
    formSchema: [],
    status: isCompleted ? 'completed' : isDraft ? 'draft' : 'published',
    results: isCompleted
      ? [{ position: '1st Place', winnerName: 'Lead Participant', projectTitle: 'Exemplary Technical Submission' }]
      : [],
    photos: [],
    publishedAt: `2026-10-0${((i % 7) + 1)}T10:00:00Z`,
    registrationsCount: 30 + ((i * 17) % 180),
    isFree: !item.paid,
    price: item.price,
    createdAt: '2026-10-01T00:00:00Z',
  })
}

console.log(`Generated ${ALL_EVENTS.length} events!`)

// Read original seedEvents.ts for registrations and everything after SEED_REGISTRATIONS
const orig = fs.readFileSync(path.join(__dirname, '../src/api/adapters/mock/seedEvents.ts'), 'utf8')
const regIndex = orig.indexOf('export const SEED_REGISTRATIONS')
if (regIndex === -1) {
  throw new Error('Could not find SEED_REGISTRATIONS in seedEvents.ts')
}
const remainder = orig.slice(regIndex)

const fileHeader = `import { Event, Registration, Certificate, Announcement, Notification, AuditLog } from '../../contracts'

export const SEED_EVENTS: Event[] = ${JSON.stringify(ALL_EVENTS, null, 2)}

`

fs.writeFileSync(path.join(__dirname, '../src/api/adapters/mock/seedEvents.ts'), fileHeader + remainder, 'utf8')
console.log('Successfully updated seedEvents.ts!')
